[phases.setup]
# nixpkgsArchive = "eb28b94bd14835836b539bc3854a6abf929876d4"
nixPkgs = ["hugo"]

[phases.build]
cmds = ["hugo"]

[environment]
HUGO_VERSION = "0.146.7"

[[nixpacks.included_files]]
paths = ["/public"]
