[phases.setup]
nixPkgs = ['nodejs_22', 'pnpm-9_x']
nixpkgsArchive = 'ac62194c3917d5f474c1a844b6fd6da2db95077d'

[phases.install]
dependsOn = ['setup']
cmds = ['pnpm i --frozen-lockfile']

[phases.build]
dependsOn = ['install']
cmds = ['pnpm run build']

[start]
cmd = 'pnpm run preview'
