[phases.setup]
nixpkgsArchive = "c11863f1e964833214b767f4a369c6e6a7aba141"
nixPkgs = ["hugo"]

[phases.build]
cmds = ["hugo"]

[environment]
HUGO_VERSION = "0.146.7"

[[nixpacks.included_files]]
paths = ["/public"]
